-- MySQL Script generated by MySQL Workbench
-- Tue Jun 24 21:07:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema frente_de_caixa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema frente_de_caixa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frente_de_caixa` DEFAULT CHARACTER SET utf8mb4 ;
USE `frente_de_caixa` ;

-- -----------------------------------------------------
-- Table `frente_de_caixa`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frente_de_caixa`.`forma_pagamento` (
  `id_forma_pagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_forma_pagamento` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_forma_pagamento`),
  UNIQUE INDEX `nome_forma_pagamento` (`nome_forma_pagamento` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frente_de_caixa`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frente_de_caixa`.`funcionario` (
  `id_funcionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `id_permissao` INT(11) NULL DEFAULT NULL,
  `funcao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frente_de_caixa`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frente_de_caixa`.`venda` (
  `id_venda` INT(11) NOT NULL AUTO_INCREMENT,
  `data_hora_venda` DATETIME NOT NULL,
  `total_venda` DECIMAL(10,2) NOT NULL,
  `id_funcionario` INT(11) NULL DEFAULT NULL,
  `id_forma_pagamento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `id_funcionario` (`id_funcionario` ASC) VISIBLE,
  INDEX `id_forma_pagamento` (`id_forma_pagamento` ASC) VISIBLE,
  CONSTRAINT `venda_ibfk_1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `frente_de_caixa`.`funcionario` (`id_funcionario`),
  CONSTRAINT `venda_ibfk_2`
    FOREIGN KEY (`id_forma_pagamento`)
    REFERENCES `frente_de_caixa`.`forma_pagamento` (`id_forma_pagamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frente_de_caixa`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frente_de_caixa`.`produto` (
  `id_produto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `estoque` INT(11) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `frente_de_caixa`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frente_de_caixa`.`item_venda` (
  `id_item_venda` INT(11) NOT NULL AUTO_INCREMENT,
  `id_venda` INT(11) NULL DEFAULT NULL,
  `id_produto` INT(11) NULL DEFAULT NULL,
  `quantidade` INT(11) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_item_venda`),
  INDEX `id_venda` (`id_venda` ASC) VISIBLE,
  INDEX `id_produto` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `item_venda_ibfk_1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `frente_de_caixa`.`venda` (`id_venda`),
  CONSTRAINT `item_venda_ibfk_2`
    FOREIGN KEY (`id_produto`)
    REFERENCES `frente_de_caixa`.`produto` (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
